version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "@typescript-eslint*"
          - "@next/eslint-plugin-next"
      vercel:
        patterns:
          - "@vercel/*"
      testing:
        patterns:
          - "@testing-library*"
          - "cypress*"
          - "jest*"
      all-others:
        patterns:
          - "*"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
